name: tactic
description: "tactic"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # 날짜/시간 지역화 지원
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI 관련 패키지
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1

  # 라우팅
  go_router: ^13.2.2

  # 네트워크 통신
  dio: ^5.7.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  http: ^1.2.2

  # 상태관리
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7

  # 코드 생성 및 데이터 처리
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.8

  # 로컬 데이터 저장
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^4.2.1
  flutter_cache_manager: ^3.4.1

  # 기타 유틸리티
  logger: ^2.5.0
  mockito: ^5.4.5
  stomp_dart_client: ^2.1.2
  fpdart: ^1.1.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
